#ifndef __LINALGTESTS_STORAGED_H__ 
#define __LINALGTESTS_STORAGED_H__ 
#include "runtime/fsharp.h"
#include <stdio.h>
#include <math.h>
#include "linalg_storaged.h"

card_t TOP_LEVEL_linalgtests_test1_shp(card_t dum_shp) {
	
	return 0;
}


void TOP_LEVEL_linalgtests_test1_dps(storage_t stgVar848, array_number_t dum_dps, card_t dum_shp) {
	card_t a_shp = 3;
	card_t size966 = width_card_t(a_shp);
	array_number_t stgVar849 = storage_alloc(size966);
	array_number_t macroDef912 = (array_number_t)stgVar849;
	macroDef912->length=3;
	macroDef912->arr=(number_t*)(STG_OFFSET(stgVar849, VECTOR_HEADER_BYTES));
	macroDef912->arr[0] = 1;
	macroDef912->arr[1] = 2;
	macroDef912->arr[2] = 3;;
	array_number_t a_dps = macroDef912;
	card_t b_shp = 3;
	card_t size965 = width_card_t(b_shp);
	array_number_t stgVar853 = storage_alloc(size965);
	array_number_t macroDef913 = (array_number_t)stgVar853;
	macroDef913->length=3;
	macroDef913->arr=(number_t*)(STG_OFFSET(stgVar853, VECTOR_HEADER_BYTES));
	macroDef913->arr[0] = 5;
	macroDef913->arr[1] = 6;
	macroDef913->arr[2] = 7;;
	array_number_t b_dps = macroDef913;
	array_print(a_dps);
	array_print(b_dps);
	card_t c_shp = TOP_LEVEL_linalg_cross_shp(a_shp, b_shp);
	card_t size964 = width_card_t(c_shp);
	array_number_t stgVar857 = storage_alloc(size964);
	array_number_t c_dps = TOP_LEVEL_linalg_cross_dps(stgVar857, a_dps, b_dps, a_shp, b_shp);
	array_print(c_dps);
	card_t d_shp = TOP_LEVEL_linalg_mult_by_scalar_shp(c_shp, 0);
	card_t size963 = width_card_t(d_shp);
	array_number_t stgVar860 = storage_alloc(size963);
	array_number_t d_dps = TOP_LEVEL_linalg_mult_by_scalar_dps(stgVar860, c_dps, 15, c_shp, 0);
	array_print(d_dps);
	card_t e_shp = TOP_LEVEL_linalg_vectorAdd_shp(a_shp, b_shp);
	card_t size962 = width_card_t(e_shp);
	array_number_t stgVar863 = storage_alloc(size962);
	array_number_t e_dps = TOP_LEVEL_linalg_vectorAdd_dps(stgVar863, a_dps, b_dps, a_shp, b_shp);
	array_print(e_dps);
	card_t f_shp = TOP_LEVEL_linalg_vectorSub_shp(a_shp, b_shp);
	card_t size961 = width_card_t(f_shp);
	array_number_t stgVar866 = storage_alloc(size961);
	array_number_t f_dps = TOP_LEVEL_linalg_vectorSub_dps(stgVar866, a_dps, b_dps, a_shp, b_shp);
	array_print(f_dps);
	card_t g_shp = TOP_LEVEL_linalg_vectorAdd3_shp(a_shp, b_shp, c_shp);
	card_t size960 = width_card_t(g_shp);
	array_number_t stgVar869 = storage_alloc(size960);
	array_number_t g_dps = TOP_LEVEL_linalg_vectorAdd3_dps(stgVar869, a_dps, b_dps, c_dps, a_shp, b_shp, c_shp);
	array_print(g_dps);
	card_t h_shp = 0;
	number_t h_dps = TOP_LEVEL_linalg_sqnorm_dps(empty_storage, a_dps, a_shp);
	number_print(h_dps);
	card_t i_shp = 0;
	number_t i_dps = TOP_LEVEL_linalg_dot_prod_dps(empty_storage, a_dps, b_dps, a_shp, b_shp);
	number_print(i_dps);
	card_t r1_shp = 3;
	card_t size959 = width_card_t(r1_shp);
	array_number_t stgVar878 = storage_alloc(size959);
	array_number_t macroDef914 = (array_number_t)stgVar878;
	macroDef914->length=3;
	macroDef914->arr=(number_t*)(STG_OFFSET(stgVar878, VECTOR_HEADER_BYTES));
	macroDef914->arr[0] = 1;
	macroDef914->arr[1] = 2;
	macroDef914->arr[2] = 3;;
	array_number_t r1_dps = macroDef914;
	card_t r2_shp = 3;
	card_t size958 = width_card_t(r2_shp);
	array_number_t stgVar882 = storage_alloc(size958);
	array_number_t macroDef915 = (array_number_t)stgVar882;
	macroDef915->length=3;
	macroDef915->arr=(number_t*)(STG_OFFSET(stgVar882, VECTOR_HEADER_BYTES));
	macroDef915->arr[0] = 4;
	macroDef915->arr[1] = 5;
	macroDef915->arr[2] = 6;;
	array_number_t r2_dps = macroDef915;
	card_t r3_shp = 3;
	card_t size957 = width_card_t(r3_shp);
	array_number_t stgVar886 = storage_alloc(size957);
	array_number_t macroDef916 = (array_number_t)stgVar886;
	macroDef916->length=3;
	macroDef916->arr=(number_t*)(STG_OFFSET(stgVar886, VECTOR_HEADER_BYTES));
	macroDef916->arr[0] = 7;
	macroDef916->arr[1] = 8;
	macroDef916->arr[2] = 9;;
	array_number_t r3_dps = macroDef916;
	matrix_shape_t mat1_shp = nested_shape_card_t(r1_shp, 3);
	card_t size956 = width_matrix_shape_t(mat1_shp);
	array_number_t stgVar890 = storage_alloc(size956);
	array_array_number_t macroDef917 = (array_array_number_t)stgVar890;
	macroDef917->length=3;
	macroDef917->arr=(array_number_t*)(STG_OFFSET(stgVar890, VECTOR_HEADER_BYTES));
	macroDef917->arr[0] = r1_dps;
	macroDef917->arr[1] = r2_dps;
	macroDef917->arr[2] = r3_dps;;
	array_array_number_t mat1_dps = macroDef917;
	matrix_shape_t n_shp = TOP_LEVEL_linalg_matrixMult_shp(mat1_shp, mat1_shp);
	card_t size955 = width_matrix_shape_t(n_shp);
	array_number_t stgVar894 = storage_alloc(size955);
	array_array_number_t n_dps = TOP_LEVEL_linalg_matrixMult_dps(stgVar894, mat1_dps, mat1_dps, mat1_shp, mat1_shp);
	matrix_print(n_dps);
	matrix_shape_t o_shp = TOP_LEVEL_linalg_matrixTranspose_shp(n_shp);
	card_t size954 = width_matrix_shape_t(o_shp);
	array_number_t stgVar897 = storage_alloc(size954);
	array_array_number_t o_dps = TOP_LEVEL_linalg_matrixTranspose_dps(stgVar897, n_dps, n_shp);
	matrix_print(o_dps);
	matrix_shape_t p_shp = TOP_LEVEL_linalg_matrixConcatCol_shp(mat1_shp, mat1_shp);
	card_t size953 = width_matrix_shape_t(p_shp);
	array_number_t stgVar899 = storage_alloc(size953);
	array_array_number_t p_dps = TOP_LEVEL_linalg_matrixConcatCol_dps(stgVar899, mat1_dps, mat1_dps, mat1_shp, mat1_shp);
	matrix_print(p_dps);
	matrix_shape_t t_shp = TOP_LEVEL_linalg_matrixAdd_shp(mat1_shp, mat1_shp);
	card_t size952 = width_matrix_shape_t(t_shp);
	array_number_t stgVar902 = storage_alloc(size952);
	array_array_number_t t_dps = TOP_LEVEL_linalg_matrixAdd_dps(stgVar902, mat1_dps, mat1_dps, mat1_shp, mat1_shp);
	matrix_print(t_dps);
	matrix_shape_t u_shp = TOP_LEVEL_linalg_matrixFillFromVector_shp(5, a_shp);
	card_t size951 = width_matrix_shape_t(u_shp);
	array_number_t stgVar905 = storage_alloc(size951);
	array_array_number_t u_dps = TOP_LEVEL_linalg_matrixFillFromVector_dps(stgVar905, 5, a_dps, 5, a_shp);
	matrix_print(u_dps);
	matrix_shape_t v_shp = TOP_LEVEL_linalg_matrixFill_shp(5, 2, 0);
	card_t size950 = width_matrix_shape_t(v_shp);
	array_number_t stgVar908 = storage_alloc(size950);
	array_array_number_t v_dps = TOP_LEVEL_linalg_matrixFill_dps(stgVar908, 5, 2, 5, 5, 2, 0);
	matrix_print(v_dps);
	;
	storage_free(stgVar908, size950);
	;
	storage_free(stgVar905, size951);
	;
	storage_free(stgVar902, size952);
	;
	storage_free(stgVar899, size953);
	;
	storage_free(stgVar897, size954);
	;
	storage_free(stgVar894, size955);
	;
	storage_free(stgVar890, size956);
	;
	storage_free(stgVar886, size957);
	;
	storage_free(stgVar882, size958);
	;
	storage_free(stgVar878, size959);
	;
	storage_free(stgVar869, size960);
	;
	storage_free(stgVar866, size961);
	;
	storage_free(stgVar863, size962);
	;
	storage_free(stgVar860, size963);
	;
	storage_free(stgVar857, size964);
	;
	storage_free(stgVar853, size965);
	;
	storage_free(stgVar849, size966);
	return ;
}
#endif
