#ifndef __LINALGTESTS_STORAGED_H__ 
#define __LINALGTESTS_STORAGED_H__ 
#include "runtime/fsharp.h"
#include <stdio.h>
#include <math.h>
#include "linalg_storaged.h"

card_t TOP_LEVEL_linalgtests_test1_shp(card_t dum_shp) {
	
	return 0;
}


void TOP_LEVEL_linalgtests_test1_dps(storage_t stgVar497, array_number_t dum_dps, card_t dum_shp) {
	card_t a_shp = 3;
	card_t size615 = width_card_t(a_shp);
	array_number_t stgVar498 = storage_alloc(size615);
	array_number_t macroDef561 = (array_number_t)stgVar498;
	macroDef561->length=3;
	macroDef561->arr=(number_t*)(STG_OFFSET(stgVar498, VECTOR_HEADER_BYTES));
	macroDef561->arr[0] = 1;
	macroDef561->arr[1] = 2;
	macroDef561->arr[2] = 3;;
	array_number_t a_dps = macroDef561;
	card_t b_shp = 3;
	card_t size614 = width_card_t(b_shp);
	array_number_t stgVar502 = storage_alloc(size614);
	array_number_t macroDef562 = (array_number_t)stgVar502;
	macroDef562->length=3;
	macroDef562->arr=(number_t*)(STG_OFFSET(stgVar502, VECTOR_HEADER_BYTES));
	macroDef562->arr[0] = 5;
	macroDef562->arr[1] = 6;
	macroDef562->arr[2] = 7;;
	array_number_t b_dps = macroDef562;
	array_print(a_dps);
	array_print(b_dps);
	card_t c_shp = TOP_LEVEL_linalg_cross_shp(a_shp, b_shp);
	card_t size613 = width_card_t(c_shp);
	array_number_t stgVar506 = storage_alloc(size613);
	array_number_t c_dps = TOP_LEVEL_linalg_cross_dps(stgVar506, a_dps, b_dps, a_shp, b_shp);
	array_print(c_dps);
	card_t d_shp = TOP_LEVEL_linalg_mult_by_scalar_shp(c_shp, 0);
	card_t size612 = width_card_t(d_shp);
	array_number_t stgVar509 = storage_alloc(size612);
	array_number_t d_dps = TOP_LEVEL_linalg_mult_by_scalar_dps(stgVar509, c_dps, 15, c_shp, 0);
	array_print(d_dps);
	card_t e_shp = TOP_LEVEL_linalg_vectorAdd_shp(a_shp, b_shp);
	card_t size611 = width_card_t(e_shp);
	array_number_t stgVar512 = storage_alloc(size611);
	array_number_t e_dps = TOP_LEVEL_linalg_vectorAdd_dps(stgVar512, a_dps, b_dps, a_shp, b_shp);
	array_print(e_dps);
	card_t f_shp = TOP_LEVEL_linalg_vectorSub_shp(a_shp, b_shp);
	card_t size610 = width_card_t(f_shp);
	array_number_t stgVar515 = storage_alloc(size610);
	array_number_t f_dps = TOP_LEVEL_linalg_vectorSub_dps(stgVar515, a_dps, b_dps, a_shp, b_shp);
	array_print(f_dps);
	card_t g_shp = TOP_LEVEL_linalg_vectorAdd3_shp(a_shp, b_shp, c_shp);
	card_t size609 = width_card_t(g_shp);
	array_number_t stgVar518 = storage_alloc(size609);
	array_number_t g_dps = TOP_LEVEL_linalg_vectorAdd3_dps(stgVar518, a_dps, b_dps, c_dps, a_shp, b_shp, c_shp);
	array_print(g_dps);
	card_t h_shp = 0;
	number_t h_dps = TOP_LEVEL_linalg_sqnorm_dps(empty_storage, a_dps, a_shp);
	number_print(h_dps);
	card_t i_shp = 0;
	number_t i_dps = TOP_LEVEL_linalg_dot_prod_dps(empty_storage, a_dps, b_dps, a_shp, b_shp);
	number_print(i_dps);
	card_t r1_shp = 3;
	card_t size608 = width_card_t(r1_shp);
	array_number_t stgVar527 = storage_alloc(size608);
	array_number_t macroDef563 = (array_number_t)stgVar527;
	macroDef563->length=3;
	macroDef563->arr=(number_t*)(STG_OFFSET(stgVar527, VECTOR_HEADER_BYTES));
	macroDef563->arr[0] = 1;
	macroDef563->arr[1] = 2;
	macroDef563->arr[2] = 3;;
	array_number_t r1_dps = macroDef563;
	card_t r2_shp = 3;
	card_t size607 = width_card_t(r2_shp);
	array_number_t stgVar531 = storage_alloc(size607);
	array_number_t macroDef564 = (array_number_t)stgVar531;
	macroDef564->length=3;
	macroDef564->arr=(number_t*)(STG_OFFSET(stgVar531, VECTOR_HEADER_BYTES));
	macroDef564->arr[0] = 4;
	macroDef564->arr[1] = 5;
	macroDef564->arr[2] = 6;;
	array_number_t r2_dps = macroDef564;
	card_t r3_shp = 3;
	card_t size606 = width_card_t(r3_shp);
	array_number_t stgVar535 = storage_alloc(size606);
	array_number_t macroDef565 = (array_number_t)stgVar535;
	macroDef565->length=3;
	macroDef565->arr=(number_t*)(STG_OFFSET(stgVar535, VECTOR_HEADER_BYTES));
	macroDef565->arr[0] = 7;
	macroDef565->arr[1] = 8;
	macroDef565->arr[2] = 9;;
	array_number_t r3_dps = macroDef565;
	matrix_shape_t mat1_shp = nested_shape_card_t(r1_shp, 3);
	card_t size605 = width_matrix_shape_t(mat1_shp);
	array_number_t stgVar539 = storage_alloc(size605);
	array_array_number_t macroDef566 = (array_array_number_t)stgVar539;
	macroDef566->length=3;
	macroDef566->arr=(array_number_t*)(STG_OFFSET(stgVar539, VECTOR_HEADER_BYTES));
	macroDef566->arr[0] = r1_dps;
	macroDef566->arr[1] = r2_dps;
	macroDef566->arr[2] = r3_dps;;
	array_array_number_t mat1_dps = macroDef566;
	matrix_shape_t n_shp = TOP_LEVEL_linalg_matrixMult_shp(mat1_shp, mat1_shp);
	card_t size604 = width_matrix_shape_t(n_shp);
	array_number_t stgVar543 = storage_alloc(size604);
	array_array_number_t n_dps = TOP_LEVEL_linalg_matrixMult_dps(stgVar543, mat1_dps, mat1_dps, mat1_shp, mat1_shp);
	matrix_print(n_dps);
	matrix_shape_t o_shp = TOP_LEVEL_linalg_matrixTranspose_shp(n_shp);
	card_t size603 = width_matrix_shape_t(o_shp);
	array_number_t stgVar546 = storage_alloc(size603);
	array_array_number_t o_dps = TOP_LEVEL_linalg_matrixTranspose_dps(stgVar546, n_dps, n_shp);
	matrix_print(o_dps);
	matrix_shape_t p_shp = TOP_LEVEL_linalg_matrixConcatCol_shp(mat1_shp, mat1_shp);
	card_t size602 = width_matrix_shape_t(p_shp);
	array_number_t stgVar548 = storage_alloc(size602);
	array_array_number_t p_dps = TOP_LEVEL_linalg_matrixConcatCol_dps(stgVar548, mat1_dps, mat1_dps, mat1_shp, mat1_shp);
	matrix_print(p_dps);
	matrix_shape_t t_shp = TOP_LEVEL_linalg_matrixAdd_shp(mat1_shp, mat1_shp);
	card_t size601 = width_matrix_shape_t(t_shp);
	array_number_t stgVar551 = storage_alloc(size601);
	array_array_number_t t_dps = TOP_LEVEL_linalg_matrixAdd_dps(stgVar551, mat1_dps, mat1_dps, mat1_shp, mat1_shp);
	matrix_print(t_dps);
	matrix_shape_t u_shp = TOP_LEVEL_linalg_matrixFillFromVector_shp(5, a_shp);
	card_t size600 = width_matrix_shape_t(u_shp);
	array_number_t stgVar554 = storage_alloc(size600);
	array_array_number_t u_dps = TOP_LEVEL_linalg_matrixFillFromVector_dps(stgVar554, 5, a_dps, 5, a_shp);
	matrix_print(u_dps);
	matrix_shape_t v_shp = TOP_LEVEL_linalg_matrixFill_shp(5, 2, 0);
	card_t size599 = width_matrix_shape_t(v_shp);
	array_number_t stgVar557 = storage_alloc(size599);
	array_array_number_t v_dps = TOP_LEVEL_linalg_matrixFill_dps(stgVar557, 5, 2, 5, 5, 2, 0);
	matrix_print(v_dps);
	;
	storage_free(stgVar557, size599);
	;
	storage_free(stgVar554, size600);
	;
	storage_free(stgVar551, size601);
	;
	storage_free(stgVar548, size602);
	;
	storage_free(stgVar546, size603);
	;
	storage_free(stgVar543, size604);
	;
	storage_free(stgVar539, size605);
	;
	storage_free(stgVar535, size606);
	;
	storage_free(stgVar531, size607);
	;
	storage_free(stgVar527, size608);
	;
	storage_free(stgVar518, size609);
	;
	storage_free(stgVar515, size610);
	;
	storage_free(stgVar512, size611);
	;
	storage_free(stgVar509, size612);
	;
	storage_free(stgVar506, size613);
	;
	storage_free(stgVar502, size614);
	;
	storage_free(stgVar498, size615);
	return ;
}
#endif
