#ifndef __LINALGTESTS_STORAGED_H__ 
#define __LINALGTESTS_STORAGED_H__ 
#include "runtime/fsharp.h"
#include <stdio.h>
#include <math.h>
#include "linalg_storaged.h"

void TOP_LEVEL_linalgtests_test1(array_number_t dum) {
	array_number_t a = (array_number_t)malloc(sizeof(int) * 2);
	a->length=3;
	a->arr = (number_t*)malloc(sizeof(number_t) * 3);
	a->arr[0] = 1;
	a->arr[1] = 2;
	a->arr[2] = 3;;
	array_number_t b = (array_number_t)malloc(sizeof(int) * 2);
	b->length=3;
	b->arr = (number_t*)malloc(sizeof(number_t) * 3);
	b->arr[0] = 5;
	b->arr[1] = 6;
	b->arr[2] = 7;;
	array_print(a);
	array_print(b);
	array_number_t c = TOP_LEVEL_linalg_cross(a, b);
	array_print(c);
	array_number_t d = TOP_LEVEL_linalg_mult_by_scalar(c, 15);
	array_print(d);
	array_number_t e = TOP_LEVEL_linalg_add_vec(a, b);
	array_print(e);
	array_number_t f = TOP_LEVEL_linalg_sub_vec(a, b);
	array_print(f);
	array_number_t g = TOP_LEVEL_linalg_add_vec3(a, b, c);
	array_print(g);
	number_t h = TOP_LEVEL_linalg_sqnorm(a);
	number_print(h);
	number_t i = TOP_LEVEL_linalg_dot_prod(a, b);
	number_print(i);
	array_number_t r1 = (array_number_t)malloc(sizeof(int) * 2);
	r1->length=3;
	r1->arr = (number_t*)malloc(sizeof(number_t) * 3);
	r1->arr[0] = 1;
	r1->arr[1] = 2;
	r1->arr[2] = 3;;
	array_number_t r2 = (array_number_t)malloc(sizeof(int) * 2);
	r2->length=3;
	r2->arr = (number_t*)malloc(sizeof(number_t) * 3);
	r2->arr[0] = 4;
	r2->arr[1] = 5;
	r2->arr[2] = 6;;
	array_number_t r3 = (array_number_t)malloc(sizeof(int) * 2);
	r3->length=3;
	r3->arr = (number_t*)malloc(sizeof(number_t) * 3);
	r3->arr[0] = 7;
	r3->arr[1] = 8;
	r3->arr[2] = 9;;
	array_array_number_t mat1 = (array_array_number_t)malloc(sizeof(int) * 2);
	mat1->length=3;
	mat1->arr = (array_number_t*)malloc(sizeof(array_number_t) * 3);
	mat1->arr[0] = r1;
	mat1->arr[1] = r2;
	mat1->arr[2] = r3;;
	array_array_number_t n = TOP_LEVEL_linalg_matrixMult(mat1, mat1);
	matrix_print(n);
	array_array_number_t o = TOP_LEVEL_linalg_matrixTranspose(n);
	matrix_print(o);
	array_array_number_t p = TOP_LEVEL_linalg_matrixConcatCol(mat1, mat1);
	matrix_print(p);
	array_array_number_t t = TOP_LEVEL_linalg_matrixAdd(mat1, mat1);
	matrix_print(t);
	array_array_number_t u = TOP_LEVEL_linalg_matrixFillFromVector(5, a);
	matrix_print(u);
	return ;
}
card_t TOP_LEVEL_linalgtests_test1_c(vector_shape_t dum_c) {
	
	return 0;
}
void TOP_LEVEL_linalgtests_test1_s(storage_t stgVar603, array_number_t dum_s, vector_shape_t dum_c) {
	vector_shape_t a_c = nested_shape_card_t(0, 3);
	array_number_t stgVar604 = malloc(width_vector_shape_t(a_c));
	array_number_t macroDef663 = (array_number_t)stgVar604;
	macroDef663->length=3;
	macroDef663->arr=(number_t*)((char*)stgVar604 + VECTOR_HEADER_BYTES);
	macroDef663->arr[0] = 1;
	macroDef663->arr[1] = 2;
	macroDef663->arr[2] = 3;;
	array_number_t a_s = macroDef663;
	vector_shape_t b_c = nested_shape_card_t(0, 3);
	array_number_t stgVar608 = malloc(width_vector_shape_t(b_c));
	array_number_t macroDef664 = (array_number_t)stgVar608;
	macroDef664->length=3;
	macroDef664->arr=(number_t*)((char*)stgVar608 + VECTOR_HEADER_BYTES);
	macroDef664->arr[0] = 5;
	macroDef664->arr[1] = 6;
	macroDef664->arr[2] = 7;;
	array_number_t b_s = macroDef664;
	array_print(a_s);
	array_print(b_s);
	vector_shape_t c_c = TOP_LEVEL_linalg_cross_c(a_c, b_c);
	array_number_t stgVar612 = malloc(width_vector_shape_t(c_c));
	array_number_t c_s = TOP_LEVEL_linalg_cross_s(stgVar612, a_s, b_s, a_c, b_c);
	array_print(c_s);
	vector_shape_t d_c = TOP_LEVEL_linalg_mult_by_scalar_c(c_c, 0);
	array_number_t stgVar615 = malloc(width_vector_shape_t(d_c));
	array_number_t d_s = TOP_LEVEL_linalg_mult_by_scalar_s(stgVar615, c_s, 15, c_c, 0);
	array_print(d_s);
	vector_shape_t e_c = TOP_LEVEL_linalg_add_vec_c(a_c, b_c);
	array_number_t stgVar618 = malloc(width_vector_shape_t(e_c));
	array_number_t e_s = TOP_LEVEL_linalg_add_vec_s(stgVar618, a_s, b_s, a_c, b_c);
	array_print(e_s);
	vector_shape_t f_c = TOP_LEVEL_linalg_sub_vec_c(a_c, b_c);
	array_number_t stgVar621 = malloc(width_vector_shape_t(f_c));
	array_number_t f_s = TOP_LEVEL_linalg_sub_vec_s(stgVar621, a_s, b_s, a_c, b_c);
	array_print(f_s);
	vector_shape_t g_c = TOP_LEVEL_linalg_add_vec3_c(a_c, b_c, c_c);
	array_number_t stgVar624 = malloc(width_vector_shape_t(g_c));
	array_number_t g_s = TOP_LEVEL_linalg_add_vec3_s(stgVar624, a_s, b_s, c_s, a_c, b_c, c_c);
	array_print(g_s);
	card_t h_c = 0;
	array_number_t stgVar628 = malloc(h_c);
	number_t h_s = TOP_LEVEL_linalg_sqnorm_s(stgVar628, a_s, a_c);
	number_print(h_s);
	card_t i_c = 0;
	array_number_t stgVar630 = malloc(i_c);
	number_t i_s = TOP_LEVEL_linalg_dot_prod_s(stgVar630, a_s, b_s, a_c, b_c);
	number_print(i_s);
	vector_shape_t r1_c = nested_shape_card_t(0, 3);
	array_number_t stgVar633 = malloc(width_vector_shape_t(r1_c));
	array_number_t macroDef665 = (array_number_t)stgVar633;
	macroDef665->length=3;
	macroDef665->arr=(number_t*)((char*)stgVar633 + VECTOR_HEADER_BYTES);
	macroDef665->arr[0] = 1;
	macroDef665->arr[1] = 2;
	macroDef665->arr[2] = 3;;
	array_number_t r1_s = macroDef665;
	vector_shape_t r2_c = nested_shape_card_t(0, 3);
	array_number_t stgVar637 = malloc(width_vector_shape_t(r2_c));
	array_number_t macroDef666 = (array_number_t)stgVar637;
	macroDef666->length=3;
	macroDef666->arr=(number_t*)((char*)stgVar637 + VECTOR_HEADER_BYTES);
	macroDef666->arr[0] = 4;
	macroDef666->arr[1] = 5;
	macroDef666->arr[2] = 6;;
	array_number_t r2_s = macroDef666;
	vector_shape_t r3_c = nested_shape_card_t(0, 3);
	array_number_t stgVar641 = malloc(width_vector_shape_t(r3_c));
	array_number_t macroDef667 = (array_number_t)stgVar641;
	macroDef667->length=3;
	macroDef667->arr=(number_t*)((char*)stgVar641 + VECTOR_HEADER_BYTES);
	macroDef667->arr[0] = 7;
	macroDef667->arr[1] = 8;
	macroDef667->arr[2] = 9;;
	array_number_t r3_s = macroDef667;
	matrix_shape_t mat1_c = nested_shape_vector_shape_t(r1_c, 3);
	array_number_t stgVar645 = malloc(width_matrix_shape_t(mat1_c));
	array_array_number_t macroDef668 = (array_array_number_t)stgVar645;
	macroDef668->length=3;
	macroDef668->arr=(array_number_t*)((char*)stgVar645 + VECTOR_HEADER_BYTES);
	macroDef668->arr[0] = r1_s;
	macroDef668->arr[1] = r2_s;
	macroDef668->arr[2] = r3_s;;
	array_array_number_t mat1_s = macroDef668;
	matrix_shape_t n_c = TOP_LEVEL_linalg_matrixMult_c(mat1_c, mat1_c);
	array_number_t stgVar649 = malloc(width_matrix_shape_t(n_c));
	array_array_number_t n_s = TOP_LEVEL_linalg_matrixMult_s(stgVar649, mat1_s, mat1_s, mat1_c, mat1_c);
	matrix_print(n_s);
	matrix_shape_t o_c = TOP_LEVEL_linalg_matrixTranspose_c(n_c);
	array_number_t stgVar652 = malloc(width_matrix_shape_t(o_c));
	array_array_number_t o_s = TOP_LEVEL_linalg_matrixTranspose_s(stgVar652, n_s, n_c);
	matrix_print(o_s);
	matrix_shape_t p_c = TOP_LEVEL_linalg_matrixConcatCol_c(mat1_c, mat1_c);
	array_number_t stgVar654 = malloc(width_matrix_shape_t(p_c));
	array_array_number_t p_s = TOP_LEVEL_linalg_matrixConcatCol_s(stgVar654, mat1_s, mat1_s, mat1_c, mat1_c);
	matrix_print(p_s);
	matrix_shape_t t_c = TOP_LEVEL_linalg_matrixAdd_c(mat1_c, mat1_c);
	array_number_t stgVar657 = malloc(width_matrix_shape_t(t_c));
	array_array_number_t t_s = TOP_LEVEL_linalg_matrixAdd_s(stgVar657, mat1_s, mat1_s, mat1_c, mat1_c);
	matrix_print(t_s);
	matrix_shape_t u_c = TOP_LEVEL_linalg_matrixFillFromVector_c(5, a_c);
	array_number_t stgVar660 = malloc(width_matrix_shape_t(u_c));
	array_array_number_t u_s = TOP_LEVEL_linalg_matrixFillFromVector_s(stgVar660, 5, a_s, 5, a_c);
	matrix_print(u_s);
	;
	free(stgVar660);
	;
	free(stgVar657);
	;
	free(stgVar654);
	;
	free(stgVar652);
	;
	free(stgVar649);
	;
	free(stgVar645);
	;
	free(stgVar641);
	;
	free(stgVar637);
	;
	free(stgVar633);
	;
	free(stgVar630);
	;
	free(stgVar628);
	;
	free(stgVar624);
	;
	free(stgVar621);
	;
	free(stgVar618);
	;
	free(stgVar615);
	;
	free(stgVar612);
	;
	free(stgVar608);
	;
	free(stgVar604);
	return ;
}
#endif
