#ifndef __LINALGTESTS_STORAGED_H__ 
#define __LINALGTESTS_STORAGED_H__ 
#include "runtime/fsharp.h"
#include <stdio.h>
#include <math.h>
#include "linalg_storaged.h"

card_t TOP_LEVEL_linalgtests_test1_c(vector_shape_t dum_c) {
	
	return 0;
}


void TOP_LEVEL_linalgtests_test1_s(storage_t stgVar457, array_number_t dum_s, vector_shape_t dum_c) {
	vector_shape_t a_c = nested_shape_card_t(0, 3);
	card_t size575 = width_vector_shape_t(a_c);
	array_number_t stgVar458 = storage_alloc(size575);
	array_number_t macroDef521 = (array_number_t)stgVar458;
	macroDef521->length=3;
	macroDef521->arr=(number_t*)(STG_OFFSET(stgVar458, VECTOR_HEADER_BYTES));
	macroDef521->arr[0] = 1;
	macroDef521->arr[1] = 2;
	macroDef521->arr[2] = 3;;
	array_number_t a_s = macroDef521;
	vector_shape_t b_c = nested_shape_card_t(0, 3);
	card_t size574 = width_vector_shape_t(b_c);
	array_number_t stgVar462 = storage_alloc(size574);
	array_number_t macroDef522 = (array_number_t)stgVar462;
	macroDef522->length=3;
	macroDef522->arr=(number_t*)(STG_OFFSET(stgVar462, VECTOR_HEADER_BYTES));
	macroDef522->arr[0] = 5;
	macroDef522->arr[1] = 6;
	macroDef522->arr[2] = 7;;
	array_number_t b_s = macroDef522;
	array_print(a_s);
	array_print(b_s);
	vector_shape_t c_c = TOP_LEVEL_linalg_cross_c(a_c, b_c);
	card_t size573 = width_vector_shape_t(c_c);
	array_number_t stgVar466 = storage_alloc(size573);
	array_number_t c_s = TOP_LEVEL_linalg_cross_s(stgVar466, a_s, b_s, a_c, b_c);
	array_print(c_s);
	vector_shape_t d_c = TOP_LEVEL_linalg_mult_by_scalar_c(c_c, 0);
	card_t size572 = width_vector_shape_t(d_c);
	array_number_t stgVar469 = storage_alloc(size572);
	array_number_t d_s = TOP_LEVEL_linalg_mult_by_scalar_s(stgVar469, c_s, 15, c_c, 0);
	array_print(d_s);
	vector_shape_t e_c = TOP_LEVEL_linalg_add_vec_c(a_c, b_c);
	card_t size571 = width_vector_shape_t(e_c);
	array_number_t stgVar472 = storage_alloc(size571);
	array_number_t e_s = TOP_LEVEL_linalg_add_vec_s(stgVar472, a_s, b_s, a_c, b_c);
	array_print(e_s);
	vector_shape_t f_c = TOP_LEVEL_linalg_sub_vec_c(a_c, b_c);
	card_t size570 = width_vector_shape_t(f_c);
	array_number_t stgVar475 = storage_alloc(size570);
	array_number_t f_s = TOP_LEVEL_linalg_sub_vec_s(stgVar475, a_s, b_s, a_c, b_c);
	array_print(f_s);
	vector_shape_t g_c = TOP_LEVEL_linalg_add_vec3_c(a_c, b_c, c_c);
	card_t size569 = width_vector_shape_t(g_c);
	array_number_t stgVar478 = storage_alloc(size569);
	array_number_t g_s = TOP_LEVEL_linalg_add_vec3_s(stgVar478, a_s, b_s, c_s, a_c, b_c, c_c);
	array_print(g_s);
	card_t h_c = 0;
	number_t h_s = TOP_LEVEL_linalg_sqnorm_s(empty_storage, a_s, a_c);
	number_print(h_s);
	card_t i_c = 0;
	number_t i_s = TOP_LEVEL_linalg_dot_prod_s(empty_storage, a_s, b_s, a_c, b_c);
	number_print(i_s);
	vector_shape_t r1_c = nested_shape_card_t(0, 3);
	card_t size568 = width_vector_shape_t(r1_c);
	array_number_t stgVar487 = storage_alloc(size568);
	array_number_t macroDef523 = (array_number_t)stgVar487;
	macroDef523->length=3;
	macroDef523->arr=(number_t*)(STG_OFFSET(stgVar487, VECTOR_HEADER_BYTES));
	macroDef523->arr[0] = 1;
	macroDef523->arr[1] = 2;
	macroDef523->arr[2] = 3;;
	array_number_t r1_s = macroDef523;
	vector_shape_t r2_c = nested_shape_card_t(0, 3);
	card_t size567 = width_vector_shape_t(r2_c);
	array_number_t stgVar491 = storage_alloc(size567);
	array_number_t macroDef524 = (array_number_t)stgVar491;
	macroDef524->length=3;
	macroDef524->arr=(number_t*)(STG_OFFSET(stgVar491, VECTOR_HEADER_BYTES));
	macroDef524->arr[0] = 4;
	macroDef524->arr[1] = 5;
	macroDef524->arr[2] = 6;;
	array_number_t r2_s = macroDef524;
	vector_shape_t r3_c = nested_shape_card_t(0, 3);
	card_t size566 = width_vector_shape_t(r3_c);
	array_number_t stgVar495 = storage_alloc(size566);
	array_number_t macroDef525 = (array_number_t)stgVar495;
	macroDef525->length=3;
	macroDef525->arr=(number_t*)(STG_OFFSET(stgVar495, VECTOR_HEADER_BYTES));
	macroDef525->arr[0] = 7;
	macroDef525->arr[1] = 8;
	macroDef525->arr[2] = 9;;
	array_number_t r3_s = macroDef525;
	matrix_shape_t mat1_c = nested_shape_vector_shape_t(r1_c, 3);
	card_t size565 = width_matrix_shape_t(mat1_c);
	array_number_t stgVar499 = storage_alloc(size565);
	array_array_number_t macroDef526 = (array_array_number_t)stgVar499;
	macroDef526->length=3;
	macroDef526->arr=(array_number_t*)(STG_OFFSET(stgVar499, VECTOR_HEADER_BYTES));
	macroDef526->arr[0] = r1_s;
	macroDef526->arr[1] = r2_s;
	macroDef526->arr[2] = r3_s;;
	array_array_number_t mat1_s = macroDef526;
	matrix_shape_t n_c = TOP_LEVEL_linalg_matrixMult_c(mat1_c, mat1_c);
	card_t size564 = width_matrix_shape_t(n_c);
	array_number_t stgVar503 = storage_alloc(size564);
	array_array_number_t n_s = TOP_LEVEL_linalg_matrixMult_s(stgVar503, mat1_s, mat1_s, mat1_c, mat1_c);
	matrix_print(n_s);
	matrix_shape_t o_c = TOP_LEVEL_linalg_matrixTranspose_c(n_c);
	card_t size563 = width_matrix_shape_t(o_c);
	array_number_t stgVar506 = storage_alloc(size563);
	array_array_number_t o_s = TOP_LEVEL_linalg_matrixTranspose_s(stgVar506, n_s, n_c);
	matrix_print(o_s);
	matrix_shape_t p_c = TOP_LEVEL_linalg_matrixConcatCol_c(mat1_c, mat1_c);
	card_t size562 = width_matrix_shape_t(p_c);
	array_number_t stgVar508 = storage_alloc(size562);
	array_array_number_t p_s = TOP_LEVEL_linalg_matrixConcatCol_s(stgVar508, mat1_s, mat1_s, mat1_c, mat1_c);
	matrix_print(p_s);
	matrix_shape_t t_c = TOP_LEVEL_linalg_matrixAdd_c(mat1_c, mat1_c);
	card_t size561 = width_matrix_shape_t(t_c);
	array_number_t stgVar511 = storage_alloc(size561);
	array_array_number_t t_s = TOP_LEVEL_linalg_matrixAdd_s(stgVar511, mat1_s, mat1_s, mat1_c, mat1_c);
	matrix_print(t_s);
	matrix_shape_t u_c = TOP_LEVEL_linalg_matrixFillFromVector_c(5, a_c);
	card_t size560 = width_matrix_shape_t(u_c);
	array_number_t stgVar514 = storage_alloc(size560);
	array_array_number_t u_s = TOP_LEVEL_linalg_matrixFillFromVector_s(stgVar514, 5, a_s, 5, a_c);
	matrix_print(u_s);
	matrix_shape_t v_c = TOP_LEVEL_linalg_matrixFill_c(5, 2, 0);
	card_t size559 = width_matrix_shape_t(v_c);
	array_number_t stgVar517 = storage_alloc(size559);
	array_array_number_t v_s = TOP_LEVEL_linalg_matrixFill_s(stgVar517, 5, 2, 5, 5, 2, 0);
	matrix_print(v_s);
	;
	storage_free(stgVar517, size559);
	;
	storage_free(stgVar514, size560);
	;
	storage_free(stgVar511, size561);
	;
	storage_free(stgVar508, size562);
	;
	storage_free(stgVar506, size563);
	;
	storage_free(stgVar503, size564);
	;
	storage_free(stgVar499, size565);
	;
	storage_free(stgVar495, size566);
	;
	storage_free(stgVar491, size567);
	;
	storage_free(stgVar487, size568);
	;
	storage_free(stgVar478, size569);
	;
	storage_free(stgVar475, size570);
	;
	storage_free(stgVar472, size571);
	;
	storage_free(stgVar469, size572);
	;
	storage_free(stgVar466, size573);
	;
	storage_free(stgVar462, size574);
	;
	storage_free(stgVar458, size575);
	return ;
}
#endif
